import type { EventFeedbackDataset } from './types'

// Auto-generated by /dev/shm/feedback/aggregate.py — do not edit by hand
// Source sheet: https://docs.google.com/spreadsheets/d/1LznaYleA2T2n0bClFcrzgXdciBRrQO_sMPFz_mC95b8/
// Responses: 23

export const dataset: EventFeedbackDataset = {
  eventId: 'd29dc7cf-2336-44ee-994e-9a917bc837d3',
  slug: 'da-masterclass-2026',
  eventName: 'The Degree Apprenticeship Masterclass',
  eventDate: '2026-02-07',
  responseCount: 23,
  sourceSheetUrl: 'https://docs.google.com/spreadsheets/d/1LznaYleA2T2n0bClFcrzgXdciBRrQO_sMPFz_mC95b8/',
  kpis: [
    {
      label: 'Responses',
      value: '23',
      tone: 'neutral',
    },
    {
      label: 'Avg value rating',
      value: '4.87/5',
      detail: '23 of 23 rated 4 or 5',
      tone: 'positive',
    },
    {
      label: 'Avg confidence after',
      value: '4.61/5',
      detail: '23 of 23 rated 4 or 5',
      tone: 'positive',
    },
    {
      label: 'Feedback helpfulness',
      value: '4.74/5',
      detail: '23 of 23 rated 4 or 5',
      tone: 'positive',
    },
  ],
  ratings: [
    {
      question: 'How valuable was the masterclass?',
      scale: [
        '1',
        '2',
        '3',
        '4',
        '5',
      ],
      counts: {
        '1': 0,
        '2': 0,
        '3': 0,
        '4': 3,
        '5': 20,
      },
      caption: 'Numeric 1–5',
      mean: 4.87,
    },
    {
      question: 'How confident do you feel about your upcoming interview?',
      scale: [
        '1',
        '2',
        '3',
        '4',
        '5',
      ],
      counts: {
        '1': 0,
        '2': 0,
        '3': 0,
        '4': 9,
        '5': 14,
      },
      caption: 'Numeric 1–5',
      mean: 4.61,
    },
    {
      question: 'How helpful was the feedback you received?',
      scale: [
        '1',
        '2',
        '3',
        '4',
        '5',
      ],
      counts: {
        '1': 0,
        '2': 0,
        '3': 0,
        '4': 6,
        '5': 17,
      },
      caption: 'Numeric 1–5',
      mean: 4.74,
    },
  ],
  testimonials: [
    {
      text: 'This was genuinely a 10/10 event. Not only did we get to speak directly to degree apprentices at prestigious firms, we were given in-depth top tips and tricks on how to perform our best at interviews. The run down of different question types for both answering and asking questions was very helpful and I think can be applied to networking generally, not only in an interview. I was fortunate enough to attend The Starting Point event and now this one too, so I can confidently say that The Steps Foundation go above and beyond to provide insightful and incredibly valuable experiences that any student would benefit from. I’m extremely grateful for these opportunities and excited for future ones!!',
      author: 'Luka C.',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 15:45:11',
    },
    {
      text: 'I joined this Degree Apprenticeship Interview Masterclass to help me through current apprenticeship applications that I am applying to and was amazed at how beneficial it was! The structure was very well planned out - one thing in particular I found useful, was the example of each tip, e.g. an example of the STAR method - this really helped me in understanding how I can use this strategy in future to help me get further in my applications. Thank you so much!',
      author: 'Francesca B.',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 15:29:39',
    },
    {
      text: 'This interview masterclass was so insightful and I gained guidance on how to answer questions and what type of questions I can ask interviewers. Jin and Favour shared many useful tips and I would definitely recommend this to other aspiring apprentices. The breakout rooms was something different but helpful as you can choose which session you want to attend based on the industry you are interested in.',
      author: 'Minal B.',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 15:27:02',
    },
    {
      text: 'This workshop made me more confident for my interview and gave me practical, actionable tips for my preparation. The hosts were very responsive to any questions asked and gave honest and detailed answers. Definitely join this workshop if you need more guidance for degree apprenticeship interviews from people who have been in the same place!',
      author: 'Romaisa Z.',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 16:15:55',
    },
    {
      text: 'This experience was truly insightful, initially I didn’t know a lot about the interview and degree apprenticeship process, but with the knowledgeable presentation from the tech hosts and main hosts, it has widened my viewpoint on how to hit an interview with the ground running',
      author: 'Abel V.',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 15:22:00',
    },
    {
      text: 'These speakers were world class experts at DAs. They answered every question so well, they guided us and gave us expert advice and overall made me ready to get into a top DA. I can\'t believe that this was free!! I shall definitely attend their next event!!',
      author: 'Yash M.',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 15:23:16',
    },
    {
      text: 'It was great! The session truly lived up to the idea that there are no stupid questions. It was really insightful, the breakout rooms felt personal, and concepts were broken down more clearly than I’ve ever experienced.',
      author: 'Aima R.',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 15:28:07',
    },
    {
      text: 'What a fantastic webinar and some really important insights into the experience of current DA. The messages that were shared around interview skills and tips were incredibly useful and I look forward for the next one.',
      author: 'William K.',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 15:26:11',
    },
  ],
  constructive: [
    {
      text: 'Thank you so much for the time you put into today. You helped us a lot with reflection, so if you’d like something to reflect on, let it be that you’ve definitely helped me today and I feel much more comfortable applying for degree apprenticeships rather than just universities. Today has changed my view massively on post-18 pathways, so thank you so much for your time!',
      author: 'Anonymous',
      context: 'Final comments',
      consent: 'anon',
      sourceTimestamp: '07/02/2026 15:53:38',
    },
    {
      text: '3) Perhaps we could have a bit more of an interactive part to the session where we actually get to practice answering the questions the same way Jin and Favour demonstrated, and you give us feedback on them, or we could have a bit of a workshop style session where we put together STARR style responses to common questions and you give us feedback on them',
      author: 'Anonymous',
      context: 'Improvement suggestions',
      consent: 'anon',
      sourceTimestamp: '07/02/2026 15:53:38',
    },
    {
      text: 'More examples. Something I think would have been beneficial to change would be to let future participants know there would be a breakout room just so people can think even harder about the best questions to ask.',
      author: 'Kyle M.',
      context: 'Improvement suggestions',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 15:29:41',
    },
    {
      text: '(1) More on application process and chances of increasing getting an interview (although I missed the start so may have been included then...\n(2) Not sure, it was all relevant \n(3) Not sure, again',
      author: 'Anonymous',
      context: 'Improvement suggestions',
      consent: 'anon',
      sourceTimestamp: '09/02/2026 17:46:34',
    },
    {
      text: 'Would there be a recording of the event/workshop, seeing as a I missed the first hour and a bit for a sporting fixture. If there is, please could I be emailed it - hopes thats okay, thanks!',
      author: 'Anonymous',
      context: 'Final comments',
      consent: 'anon',
      sourceTimestamp: '09/02/2026 17:46:34',
    },
    {
      text: 'Jim Samson is so incredibly good at talking and effectively communicating, his advice about consulting and how to engage with the interviewer were really intriguing and useful.',
      author: 'Anonymous',
      context: 'Final comments',
      consent: 'no',
      sourceTimestamp: '07/02/2026 15:22:18',
    },
    {
      text: 'Thank you for another incredible event, the whole team are so well-spoken and inspiring and I’m very excited for future events!!!',
      author: 'Luka C.',
      context: 'Final comments',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 15:45:11',
    },
    {
      text: 'Less answers that we can find the information to via the internet am more specific knowledge that can only be answered by people',
      author: 'Ismaìl a.',
      context: 'Improvement suggestions',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 15:29:11',
    },
  ],
  growth: [
    {
      text: 'This workshop made me more confident for my interview and gave me practical, actionable tips for my preparation. The hosts were very responsive to any questions asked and gave honest and detailed answers. Definitely join this workshop if you need more guidance for degree apprenticeship interviews from people who have been in the same place!',
      author: 'Romaisa Z.',
      context: 'Testimonial',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 16:15:55',
    },
    {
      text: 'These speakers were world class experts at DAs. They answered every question so well, they guided us and gave us expert advice and overall made me ready to get into a top DA. I can\'t believe that this was free!! I shall definitely attend their next event!!',
      author: 'Yash M.',
      context: 'Testimonial',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 15:23:16',
    },
    {
      text: 'I had a great experience and learnt a lot of key information and alot of information I woudl not be able to find on google or chatgpt and really opened my eyes on interviews and how to prepare for them',
      author: 'Ismaìl a.',
      context: 'Testimonial',
      consent: 'first_name',
      sourceTimestamp: '07/02/2026 15:29:11',
    },
    {
      text: 'The workshop was an incredible experience, very eye opening into the process of applying to and gaining an apprenticeship, alongside a degree. For anyone interested in a Degree Apprenticeship, the Masterclass is a must-watch for specific advantage in securing careers such as Investment Banking, Consulting, Management, Law,  Software Engineering and more.',
      author: 'Anonymous',
      context: 'Testimonial',
      consent: 'anon',
      sourceTimestamp: '09/02/2026 17:46:34',
    },
    {
      text: 'This masterclass was honestly incredible, the speakers really made me feel more confident going into other interviews, and they answered all my questions clearing up any misconceptions or confusions I had. Jins consulting session was so helpful for me, giving quality advice for final interviews and overall tech roles in consulting. Thank you!!',
      author: 'Anonymous',
      context: 'Testimonial',
      consent: 'anon',
      sourceTimestamp: '07/02/2026 15:20:22',
    },
    {
      text: 'I applied for this not 100% on if it would help me but now I’m going to leave soon with more confidence in myself and useful knowledge in how to increase the chances of succeeding in my interviews.',
      author: 'Anonymous',
      context: 'Testimonial',
      consent: 'anon',
      sourceTimestamp: '07/02/2026 15:20:29',
    },
  ],
  appendix: [
    {
      timestamp: '07/02/2026 15:19:56',
      name: 'Faozan Q.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'The difference between a good interview and a great interview, star method, Ricardo had some really great points.',
      },
    },
    {
      timestamp: '07/02/2026 15:20:19',
      name: 'Kyle F.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'Do your research!',
        'Improvement suggestions': '1. More speakers',
        Testimonial: 'Great session!',
      },
    },
    {
      timestamp: '07/02/2026 15:20:22',
      name: 'Hafsa A.',
      consent: 'anon',
      fields: {
        'Most important thing learnt': 'Asking questions to the interviewer - really prepared me for future interviews!!',
        Testimonial: 'This masterclass was honestly incredible, the speakers really made me feel more confident going into other interviews, and they answered all my questions clearing up any misconceptions or confusions I had. Jins consulting session was so helpful for me, giving quality advice for final interviews and overall tech roles in consulting. Thank you!!',
      },
    },
    {
      timestamp: '07/02/2026 15:20:29',
      name: 'Rosaria B.',
      consent: 'anon',
      fields: {
        'Most important thing learnt': 'To learn more about your interviewer and the company before the interview.',
        'Improvement suggestions': 'Nothing! This was perfect',
        Testimonial: 'I applied for this not 100% on if it would help me but now I’m going to leave soon with more confidence in myself and useful knowledge in how to increase the chances of succeeding in my interviews.',
      },
    },
    {
      timestamp: '07/02/2026 15:20:51',
      name: 'Krish G.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'Importance of asking questions to interviewer',
      },
    },
    {
      timestamp: '07/02/2026 15:22:00',
      name: 'Abel V.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'That coming to an interview fully prepared with releavant and unique research can be the main factor point to getting that job',
        Testimonial: 'This experience was truly insightful, initially I didn’t know a lot about the interview and degree apprenticeship process, but with the knowledgeable presentation from the tech hosts and main hosts, it has widened my viewpoint on how to hit an interview with the ground running',
      },
    },
    {
      timestamp: '07/02/2026 15:22:18',
      name: 'Haleema C.',
      consent: 'no',
      fields: {
        'Most important thing learnt': 'Learned a lot about the interview process and how to effectively story tell and make the interview more engaging.',
        'Final comments': 'Jim Samson is so incredibly good at talking and effectively communicating, his advice about consulting and how to engage with the interviewer were really intriguing and useful.',
      },
    },
    {
      timestamp: '07/02/2026 15:22:41',
      name: 'Stanley W.',
      consent: 'anon',
      fields: {
        'Most important thing learnt': 'To have story banks prepared for interview',
        Testimonial: 'A fantastic experience that really helped me through how to deal with interviews',
        'Final comments': 'please make the slides/notes/recording available for those who attended',
      },
    },
    {
      timestamp: '07/02/2026 15:23:16',
      name: 'Yash M.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'That degree apprenticeships are amazing',
        'Improvement suggestions': 'More guests so we can see more different career options',
        Testimonial: 'These speakers were world class experts at DAs. They answered every question so well, they guided us and gave us expert advice and overall made me ready to get into a top DA. I can\'t believe that this was free!! I shall definitely attend their next event!!',
        'Final comments': 'Masterpiece',
      },
    },
    {
      timestamp: '07/02/2026 15:23:49',
      name: 'Darshan A.',
      consent: 'anon',
      fields: {
        'Most important thing learnt': 'Researching your interviewers!',
        'Improvement suggestions': '1) Live interview questions and responses, involving the participants',
        Testimonial: 'Such an amazing experience, and it was amazing we got it tailored to our industrial preferences!',
        'Final comments': 'Cheers Dani, Jin, Favour and Earl for putting on all these amazing events!',
      },
    },
    {
      timestamp: '07/02/2026 15:26:11',
      name: 'William K.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'How to successfully answer interview questions',
        'Improvement suggestions': 'More time with the current DA\nNothing less\nSome more CV advice',
        Testimonial: 'What a fantastic webinar and some really important insights into the experience of current DA. The messages that were shared around interview skills and tips were incredibly useful and I look forward for the next one.',
        'Final comments': 'Just wanted to say thank you for the event and how well it was delivered .',
      },
    },
    {
      timestamp: '07/02/2026 15:27:02',
      name: 'Minal B.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'I learn’t about storytelling and how to use it in interview answers.',
        Testimonial: 'This interview masterclass was so insightful and I gained guidance on how to answer questions and what type of questions I can ask interviewers. Jin and Favour shared many useful tips and I would definitely recommend this to other aspiring apprentices. The breakout rooms was something different but helpful as you can choose which session you want to attend based on the industry you are interested in.',
      },
    },
    {
      timestamp: '07/02/2026 15:28:07',
      name: 'Aima R.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'Be teachable.',
        'Improvement suggestions': 'Nothing',
        Testimonial: 'It was great! The session truly lived up to the idea that there are no stupid questions. It was really insightful, the breakout rooms felt personal, and concepts were broken down more clearly than I’ve ever experienced.',
        'Final comments': 'Thanks guys :)',
      },
    },
    {
      timestamp: '07/02/2026 15:29:11',
      name: 'Ismaìl a.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'How to prepare stories to hit all skills when asked star method questions',
        'Improvement suggestions': 'Less answers that we can find the information to via the internet am more specific knowledge that can only be answered by people',
        Testimonial: 'I had a great experience and learnt a lot of key information and alot of information I woudl not be able to find on google or chatgpt and really opened my eyes on interviews and how to prepare for them',
      },
    },
    {
      timestamp: '07/02/2026 15:29:39',
      name: 'Francesca B.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'The example of Storytelling was incredibly helpful in understanding how we can twist our answers slightly just to make it sound less robotic, and much more genuine.',
        'Improvement suggestions': 'Not applicable - this webinar covered every aspect l- structured very well!',
        Testimonial: 'I joined this Degree Apprenticeship Interview Masterclass to help me through current apprenticeship applications that I am applying to and was amazed at how beneficial it was! The structure was very well planned out - one thing in particular I found useful, was the example of each tip, e.g. an example of the STAR method - this really helped me in understanding how I can use this strategy in future to help me get further in my applications. Thank you so much!',
      },
    },
    {
      timestamp: '07/02/2026 15:29:41',
      name: 'Kyle M.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'The importance of storytelling',
        'Improvement suggestions': 'More examples. Something I think would have been beneficial to change would be to let future participants know there would be a breakout room just so people can think even harder about the best questions to ask.',
        Testimonial: 'Really useful overall with lots of great opportunities to ask questions. Unmatched advice on how to prepare and overall really insightful. No changes really needed as it’s already extremely useful.',
      },
    },
    {
      timestamp: '07/02/2026 15:30:07',
      name: 'Nuo H.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'The most important thing I learnt is how crucial it is to build rapport with your interviewer and making it personal by turning the actual interview into a conversation.',
        'Improvement suggestions': '1) How to write the perfect CV and cover letter\nbut apart from that it was brilliant',
        Testimonial: 'Very insightful and beneficial. Definitely recommend for future DA applicants',
      },
    },
    {
      timestamp: '07/02/2026 15:42:58',
      name: 'Esa B.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'Understanding the importance of building a story bank before interviews and how it helps structure answers effectively.',
        'Improvement suggestions': 'Nothing major. Maybe a little extra time in the breakout rooms, as the session ended while the speaker was still talking.',
        Testimonial: 'The workshop was extremely insightful and valuable in helping me understand how to ace degree apprenticeship interviews. I\'d absolutely recommend it to any prospective DA applicants.',
        'Final comments': 'No further questions. Thank you to the speakers for such a helpful and informative workshop',
      },
    },
    {
      timestamp: '07/02/2026 15:43:27',
      name: 'Ryan N.',
      consent: 'no',
      fields: {
        'Most important thing learnt': 'Learning how to build rapport with the interviewer and also how to make sure my answers always relate to the firm, their values and strategy.',
      },
    },
    {
      timestamp: '07/02/2026 15:45:11',
      name: 'Luka C.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'It’s very difficult to narrow it down, but Luca mentioned how mistakes are not the end, the important factor is how you come back from them and I think that is amazing advice. Also of course the step by step framework is an wonderful summary of the whole event.',
        'Improvement suggestions': '(1) I would have liked even more time to speak to all the of the speakers.',
        Testimonial: 'This was genuinely a 10/10 event. Not only did we get to speak directly to degree apprentices at prestigious firms, we were given in-depth top tips and tricks on how to perform our best at interviews. The run down of different question types for both answering and asking questions was very helpful and I think can be applied to networking generally, not only in an interview. I was fortunate enough to attend The Starting Point event and now this one too, so I can confidently say that The Steps Foundation go above and beyond to provide insightful and incredibly valuable experiences that any student would benefit from. I’m extremely grateful for these opportunities and excited for future ones!!',
        'Final comments': 'Thank you for another incredible event, the whole team are so well-spoken and inspiring and I’m very excited for future events!!!',
      },
    },
    {
      timestamp: '07/02/2026 15:53:38',
      name: 'Shifa M.',
      consent: 'anon',
      fields: {
        'Most important thing learnt': 'Spending time learning about the company and interviewer is definitely worth it and can be incredibly valuable',
        'Improvement suggestions': '3) Perhaps we could have a bit more of an interactive part to the session where we actually get to practice answering the questions the same way Jin and Favour demonstrated, and you give us feedback on them, or we could have a bit of a workshop style session where we put together STARR style responses to common questions and you give us feedback on them',
        Testimonial: 'After attending this workshop, my confidence as an interviewee has excelled, and I feel so much more comfortable in applying for degree apprenticeships alongside universities, rather than choosing the “traditional” or “safe” route of university. Thank you so much - highly recommend!',
        'Final comments': 'Thank you so much for the time you put into today. You helped us a lot with reflection, so if you’d like something to reflect on, let it be that you’ve definitely helped me today and I feel much more comfortable applying for degree apprenticeships rather than just universities. Today has changed my view massively on post-18 pathways, so thank you so much for your time!',
      },
    },
    {
      timestamp: '07/02/2026 16:15:55',
      name: 'Romaisa Z.',
      consent: 'first_name',
      fields: {
        'Most important thing learnt': 'Technical knowledge isn’t expected. Be familiar with macroeconomic events and listen to podcasts to know how to confidently talk about the industry.',
        'Improvement suggestions': '1) more example answers\n3) a short interview example being played out',
        Testimonial: 'This workshop made me more confident for my interview and gave me practical, actionable tips for my preparation. The hosts were very responsive to any questions asked and gave honest and detailed answers. Definitely join this workshop if you need more guidance for degree apprenticeship interviews from people who have been in the same place!',
        'Final comments': 'Could you make a handbook about CVs and cover letters?',
      },
    },
    {
      timestamp: '09/02/2026 17:46:34',
      name: 'Mustafah K.',
      consent: 'anon',
      fields: {
        'Most important thing learnt': 'The STARR method was quite good, I look forward to using it and testing it over the course of my application process.',
        'Improvement suggestions': '(1) More on application process and chances of increasing getting an interview (although I missed the start so may have been included then...\n(2) Not sure, it was all relevant \n(3) Not sure, again',
        Testimonial: 'The workshop was an incredible experience, very eye opening into the process of applying to and gaining an apprenticeship, alongside a degree. For anyone interested in a Degree Apprenticeship, the Masterclass is a must-watch for specific advantage in securing careers such as Investment Banking, Consulting, Management, Law,  Software Engineering and more.',
        'Final comments': 'Would there be a recording of the event/workshop, seeing as a I missed the first hour and a bit for a sporting fixture. If there is, please could I be emailed it - hopes thats okay, thanks!',
      },
    },
  ],
}

export default dataset
